defaults:
  - dataset:
  - retriever:
  - chunker:
  - prompts:
  - reranker:
  - indexer:
  - generator:
  - _self_

hydra:
  run:
    dir: dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${dataset.name}_${retriever.name}_${reranker.name}_${indexer.name}_${generator.name}
  job:
    chdir: true
