defaults:
  - dataset: hotpot_mini
  - retriever: bm25
  - chunker: recursive
  - prompts: base
  - reranker: none
  - indexer: inmemory
  - generator: echo
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${dataset.name}_${retriever.name}_${reranker.name}_${indexer.name}_${generator.name}
  job:
    chdir: true
